// Begining and ending tag for the preview block.
export const BEGIN_TAG = '/// --- [MLIR_INC_PREVIEW_START] ---';
export const END_TAG = '/// --- [MLIR_INC_PREVIEW_END] ---';

// End comment line for the original include line.
export const BEGIN_COMMENT_LINE = '/// ';
export const END_COMMENT_LINE =
    ' /// <- GENERATED BY MLIR INC PREVIEWER! DON\'T EDIT!';

// How many lines to search for an include line from the current line (upwards
// and downwards).
export const SearchIncLineRange = 3;

// Whether to open the preview window automatically when showing help.
export const ifPreviewReadme = false;
