// Copyright (c) 2026 Jianchao Yang
// Licensed under the MIT License - see the LICENSE file for details.

// Begining and ending tag for the preview block.
export const BEGIN_TAG = '/// --- [MLIR_INC_PREVIEW_START] ---';
export const END_TAG = '/// --- [MLIR_INC_PREVIEW_END] ---';

// End comment line for the original include line.
export const BEGIN_COMMENT_LINE = '/// ';
export const END_COMMENT_LINE =
    ' /// <- GENERATED BY MLIR INC PREVIEWER! DON\'T EDIT!';

// How many lines to search for an include line from the current line (upwards
// and downwards).
export const SearchIncLineRange = 3;

// Whether to open the preview window automatically when showing help.
export const ifPreviewReadme = false;

// Whether to enable removing unrelated preview blocks based on the current
// file's conditional compilation when expanding the preview.
//
// TODO: This feature is only available when all preview blocks are expanded
//       in the order of line numbers in the text. In other situations (not
//       in order or choosing to expand all), there are currently bugs:
//       1. Not in order: A later preview block cannot know the conditional
//          compilation statements in preceding preview blocks that have not
//          been expanded.
//       2. Choosing to expand all: In the current version, expanding all is
//          done in reverse order, so it also encounters the same problem as
//          expanding out of order.
export const ifRemoveUnrelatedPreviewBlocks = false;
